---
title: "T0 INTRO"
author: "Guillermo Lopez Taboada"
date: "14/09/2020"
output: pdf_document
---

Introducción a las Tecnologías de Gestión y Manipulación de Datos
=================================================================


```{r , child = '_global_options.Rmd'}
```

<!-- ## Introducción -->


La información relevante de la materia está disponible en la guía docente y la ficha de la asignatura

En particular, los resultados de aprendizaje son:

* Manejar de forma autónoma y solvente el software necesario para acceder a conjuntos de datos en entornos profesionales y/o en la nube.	

* Saber gestionar conjuntos de datos masivos en un entorno multidisciplinar que permita la participación en proyectos profesionales complejos que requieran el uso de técnicas estadísticas.	

* Saber relacionar el software de diseño y gestión de bases de datos con el específicamente implementado para el análisis de datos.

## Contenidos

1. Introducción al lenguaje SQL	
	+ Bases de datos relacionales
	+ Sintaxis SQL
	+ Conexión con bases de datos desde R
2. Introducción a tecnologías NoSQL	
	+ Conceptos y tipos de bases de datos NoSQL (documental, columnar, clave/valor y de grafos)
	+ Conexión de R a NoSQL
3. Tecnologías para el tratamiento de datos masivos	
	+ Tecnologías Big Data
	+ Visualización y generación de cuadros de mando 
	+ Introducción al análisis de datos masivos.


## Planificación (tentativa)

La impartición de los contenidos durante el curso dependerá de los conocimientos de partida y la asimilación de los 
conceptos. Para completar nuestra visión de los conocimientos previos os requerimos completar este formulario en la primera sesión de clase: https://forms.gle/9HR5iFHXoLowrCHLA

- Clase 1 (14/9): Presentación e introducción a Tema 1.

- Clase 2 (17/9): Tema 1: Introducción a SQL

- Clase 3 (21/9-RFC): Seminario Manipulación de datos con R 
- Clase 4 (24/9-RFC): Seminario Manipulación de datos con dplyr

- Clase 5 (28/9): Tema 1: Ejercicios SQL

- Clase 6 (1/10): Tema 1: Ejercicios SQL 

- Clase 7 (5/10): Tema 2: Introducción a NoSQL

- Clase 8 (8/10): Tema 2: Ejercicios NoSQL

- Clase 9 (19/10): Tema 2:  Ejercicios con formatos Open Data 

- Clase 10 (26/10): Tema 3: Ecosistema Big Data 

- Clase 11-20 (2/11 al 3/12): Tema 3: Ecosistema Big Data (teoría, práctica) + Seminario de aprendizaje estadístico (3 sesiones con RFC)

No tendremos clase el 7 de Diciembre.

- Clases 21-23 (10, 14 y 17/12): Tema 3: Ejercicios Big Data


<!-- Curso 2019-2020

- Clase 1 (12/9-R): Seminario R (Manipulación de datos con el paquete base de R)

- Clase 2 (19/9): Tema 1: Conceptos de bases de datos

- Clase 3 (26/9): Tema 1: Introducción a SQL

- Clase 4 (3/10-R): Seminario dplyr (Manipulación de datos con el paquete dplyr)

- Clase 5 (10/10): Jornada usuarios R Galicia (cubre objetivos de Seminario aplicaciones Big Data en investigación e industria)

- Clase 6 (17/10): Tema 1: Ejercicios prácticos de Entidad-relación y SQL

- Clase 7 (24/10): Tema 2: Introducción a NoSQL

- Clase 8 (31/10):  Tema 1: Continuación de ejercicios prácticos SQL

- Clase 9 (7/11):  Tema 2: Ejercicios prácticos de NoSQL

- Clase 10 (14/11):   Seminario visualización con power BI

- Clase 11 (21/11):  Tema 3: Ecosistema Big Data (Hadoop, Spark)

- Clase 12 (28/11):  Tecnologías Big Data (Rspark/sparklyr) + Seminario machine learning CESGA/localhost

- Clase 13 (5/12): Tema 3: Introducción al análisis de datos masivos son sparklyr

- Clase 14 (12/12): Tema 3: Prácticas de Aprendizaje Estadístico/Automático, Data Mining con rattle

- Clase 15 (19/12-R): Seminario conectividad dplyr a BBDD

-->

### Evaluación

-   **Examen** (60%): El examen de la materia evaluará los siguientes aspectos: 
Conceptos de la materia: Dominio de los conocimientos teóricos y operativos de la materia.
Asimilación práctica de materia: Asimilación y comprensión de los conocimientos teóricos y operativos de la materia.

-   **Prácticas de laboratorio** (30%): Evaluación de las prácticas de laboratorio desarrolladas por los estudiantes.

-   **Trabajos tutelados** (10%): Evaluación de los trabajos tutelados desarrollados por los estudiantes.


#### Observaciones sobre la evaluación:

* Las prácticas de laboratorio se realizarán de forma individual, así como el trabajo tutelado que es opcional. En caso de no realizar el trabajo tutelado los estudiantes tendrán un 67% de nota del examen y un 33% de prácticas de laboratorio. El plazo para realizar las 3 prácticas será indicado en la presentación de la práctica. El plazo para la entrega de los trabajos tutelados es el último día de clase de la asignatura.

* El estudiante que quiera realizar un trabajo tutelado ha de hablar (o mediante correo electrónico) con los profesores para validar y confirmar el tema y alcance del trabajo tutelado.

* Para poder aprobar la asignatura en la primera oportunidad será necesario obtener como mínimo el 30% de la nota máxima de la suma de las prácticas de laboratorio y trabajos tutelados e, igualmente, el 30% de la nota máxima final de la Prueba mixta (examen), y tener una nota total (prácticas más trabajos tutelados más prueba mixta) igual o superior al 50% de la nota máxima.

* En la segunda oportunidad solamente se podrá recuperar la nota del examen. Las notas de prácticas y de trabajos tutelados serán las obtenidas durante el curso. Para los alumnos que utilicen la oportunidad adelantada de diciembre se utilizarán las notas de prácticas y trabajos tutelados que obtuvieran en su último curso. En esta oportunidad solo será necesario para aprobar obtener una nota total igual o superior al 50% de la nota máxima.

* Una vez que un estudiante es evaluado en una práctica de laboratorio o en un trabajo tutelado implica que será calificado. Por tanto, la calificación "No Presentado" no es posible una vez que una práctica/trabajo ha sido evaluada.

## Fuentes de información:

### Básica

* Daroczi, G. (2015). Mastering Data Analysis with R. Packt Publishing

* Grolemund, G. y Wickham, H. (2016). R for Data Science. https://r4ds.had.co.nz/ & O'Reilly

* Silberschatz, A., Korth, H. y Sudarshan, S. (2014). Fundamentos de Bases de Datos. Mc Graw Hill

* Rubén Fernández Casal ([R Machinery](https://rubenfcasal.github.io)):

    - [Introducción al Análisis de Datos con R ](https://rubenfcasal.github.io/intror)
      (con Javier Roca y Julián Costa)
    
    - [Ayuda y Recursos para el Aprendizaje de R ](https://rubenfcasal.github.io/post/ayuda-y-recursos-para-el-aprendizaje-de-r)
    
    - [Escritura de libros con el paquete bookdown ](https://rubenfcasal.github.io/bookdown_intro)
      (con Tomás Cotos)
    
    - [Apéndice introducción a Rmarkdown ](https://rubenfcasal.github.io/bookdown_intro/rmarkdown.html) 
    
    - [Pesentación análisis de datos con R ](https://rubenfcasal.github.io/post/presentaciones/AnalisisDatosR.pdf)
    

### Complementaria:

* Wes McKinney (2017). Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython. O'Reilly (2ª ed.)
* Tom White (2015). Hadoop: The Definitive Guide. O'Reilly (4ª ed.)
* Alex Holmes (2014). Hadoop in practice. Manning (2ª ed.)
* Centro de Supercomputación de Galicia (2019). Servicio de Big Data del CESGA. https://bigdata.cesga.es/


